Wallnut-SuperMarket/Models/Item.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallnut_SuperMarket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Item
    {
        public int id { get; set; }
        public string name { get; set; }
        [DisplayName("counter")]
        public int counterId { get; set; }
        [DisplayName("category")]
        public int categoryId { get; set; }
        public string brand { get; set; }
        [DisplayName("unit price")]
        public Nullable<float> rating { get; set; }
        public string picture { get; set; }
        public Nullable<int> stock { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}

Wallnut-SuperMarket/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Wallnut_SuperMarket.Models;
using System.IO;


namespace Wallnut_SuperMarket.Controllers
{
    public class ItemsController : Controller
    {
        private WallnutDatabaseEntities6 db = new WallnutDatabaseEntities6();

        // Admin
        // GET: Items
        public async Task<ActionResult> Index()
        {
            WallnutDatabaseEntities2 counterDb = new WallnutDatabaseEntities2();
            WallnutDatabaseEntities4 categoryDb = new WallnutDatabaseEntities4();

            List<Counter> counterList = await counterDb.Counters.ToListAsync();
            List<Category> categoryList = await categoryDb.Categories.ToListAsync();

            ViewData["counterList"] = counterList;
            ViewData["categoryList"] = categoryList;

            return View(await db.Items.ToListAsync());
        }

        // Admin
        // GET: Items/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            WallnutDatabaseEntities2 counterDb = new WallnutDatabaseEntities2();
            WallnutDatabaseEntities4 categoryDb = new WallnutDatabaseEntities4();

            List<Counter> counterList = await counterDb.Counters.ToListAsync();
            List<Category> categoryList = await categoryDb.Categories.ToListAsync();

            ViewData["counterList"] = counterList;
            ViewData["categoryList"] = categoryList;

            return View(item);
        }

        // Admin
        // GET: Items/Create
        public async Task<ActionResult> Create()
        {
            WallnutDatabaseEntities2 counterDb = new WallnutDatabaseEntities2();
            WallnutDatabaseEntities4 categoryDb = new WallnutDatabaseEntities4();

            List<Counter> counterList = await counterDb.Counters.ToListAsync();
            List<Category> categoryList = await categoryDb.Categories.ToListAsync();

            ViewData["counterList"] = counterList;
            ViewData["categoryList"] = categoryList;

            return View();
        }

        // Admin
        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Item item)
        {
            string fileName = Path.GetFileNameWithoutExtension(item.ImageFile.FileName);
            string extension = Path.GetExtension(item.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            item.picture = "~/ImageItem/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/ImageItem/"), fileName);
            item.ImageFile.SaveAs(fileName);

            db.Items.Add(item);
            db.SaveChanges();
            ModelState.Clear();

            return RedirectToAction("Index");
        }

        // Admin
        // GET: Items/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            WallnutDatabaseEntities2 counterDb = new WallnutDatabaseEntities2();
            WallnutDatabaseEntities4 categoryDb = new WallnutDatabaseEntities4();

            List<Counter> counterList = await counterDb.Counters.ToListAsync();
            List<Category> categoryList = await categoryDb.Categories.ToListAsync();

            ViewData["counterList"] = counterList;
            ViewData["categoryList"] = categoryList;

            return View(item);
        }

        // Admin
        // GET: Items/AddStock/5
        public async Task<ActionResult> AddStock(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            WallnutDatabaseEntities2 counterDb = new WallnutDatabaseEntities2();
            WallnutDatabaseEntities4 categoryDb = new WallnutDatabaseEntities4();

            List<Counter> counterList = await counterDb.Counters.ToListAsync();
            List<Category> categoryList = await categoryDb.Categories.ToListAsync();

            ViewData["counterList"] = counterList;
            ViewData["categoryList"] = categoryList;

            return View(item);
        }

        // Admin
        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,name,counterId,categoryId,brand,rating,picture,stock")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            WallnutDatabaseEntities2 counterDb = new WallnutDatabaseEntities2();
            WallnutDatabaseEntities4 categoryDb = new WallnutDatabaseEntities4();

            List<Counter> counterList = await counterDb.Counters.ToListAsync();
            List<Category> categoryList = await categoryDb.Categories.ToListAsync();

            ViewData["counterList"] = counterList;
            ViewData["categoryList"] = categoryList;

            return View(item);
        }

        // Admin
        // POST: Items/AddStock/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddStock([Bind(Include = "id,name,counterId,categoryId,brand,rating,picture,stock")] Item item)
        {
            if (ModelState.IsValid)
            {
                Item itemFromDb = await db.Items.FindAsync(item.id);
                itemFromDb.stock = itemFromDb.stock + item.stock;

                db.Entry(itemFromDb).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            WallnutDatabaseEntities2 counterDb = new WallnutDatabaseEntities2();
            WallnutDatabaseEntities4 categoryDb = new WallnutDatabaseEntities4();

            List<Counter> counterList = await counterDb.Counters.ToListAsync();
            List<Category> categoryList = await categoryDb.Categories.ToListAsync();

            ViewData["counterList"] = counterList;
            ViewData["categoryList"] = categoryList;

            return View(item);
        }

        // Admin
        // GET: Items/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            WallnutDatabaseEntities2 counterDb = new WallnutDatabaseEntities2();
            WallnutDatabaseEntities4 categoryDb = new WallnutDatabaseEntities4();

            List<Counter> counterList = await counterDb.Counters.ToListAsync();
            List<Category> categoryList = await categoryDb.Categories.ToListAsync();

            ViewData["counterList"] = counterList;
            ViewData["categoryList"] = categoryList;

            return View(item);
        }

        // Admin
        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Item item = await db.Items.FindAsync(id);
            db.Items.Remove(item);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Wallnut-SuperMarket/Views/Items/AddStock.cshtml
@model Wallnut_SuperMarket.Models.Item

@{
    ViewBag.Title = "AddStock";
}

<h2>AddStock</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                <p>@Model.name</p>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.counterId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.counterId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.counterId, "", new { @class = "text-danger" })
                @{
                    var counterList = (List<Wallnut_SuperMarket.Models.Counter>)ViewData["counterList"];
                    foreach (var counter in counterList)
                    {
                        if (counter.id == Model.counterId)
                        {
                            <p>@counter.counter1</p>
                        }
                    }
                }
                @Html.ValidationMessageFor(model => model.counterId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.categoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryId, "", new { @class = "text-danger" })
                @{
                    var categoryList = (List<Wallnut_SuperMarket.Models.Category>)ViewData["categoryList"];
                    foreach (var category in categoryList)
                    {
                        if (category.id == Model.categoryId)
                        {
                            <p>@category.name</p>
                        }
                    }
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.brand, "", new { @class = "text-danger" })
                <p>@Model.brand</p>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
                <p>@Model.rating</p>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                @Html.HiddenFor(model => model.picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="number" id="stock" name="stock" class="form-control" />
                @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Wallnut-SuperMarket/Views/Items/Create.cshtml
@model Wallnut_SuperMarket.Models.Item

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Items", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Item</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.counterId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select class="form-control" id="counterId" name="counterId">
                <option value="0">Select a counter</option>
                @{
                    var counterList = (List<Wallnut_SuperMarket.Models.Counter>)ViewData["counterList"];
                    foreach (var counter in counterList)
                    {
                        <option value="@counter.id">@counter.counter1</option>
                    }
                }
            </select>
            @Html.ValidationMessageFor(model => model.counterId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.categoryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select class="form-control" id="categoryId" name="categoryId">
                <option value="0">Select a category</option>
                @{
                    var categoryList = (List<Wallnut_SuperMarket.Models.Category>)ViewData["categoryList"];
                    foreach (var category in categoryList)
                    {
                        <option value="@category.id">@category.name</option>
                    }
                }
            </select>
            @Html.ValidationMessageFor(model => model.categoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.brand, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.brand, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.brand, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.picture, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input class="form-control" type="file" name="ImageFile" required />
            @Html.ValidationMessageFor(model => model.picture, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.stock, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Wallnut-SuperMarket/Views/Items/Delete.cshtml
@model Wallnut_SuperMarket.Models.Item

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.counterId)
        </dt>

        <dd>
            @{
                var counterList = (List<Wallnut_SuperMarket.Models.Counter>)ViewData["counterList"];
                foreach (var counter in counterList)
                {
                    if (counter.id == Model.counterId)
                    {
                        <p>@counter.counter1</p>
                    }
                }
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoryId)
        </dt>

        <dd>
            @{
                var categoryList = (List<Wallnut_SuperMarket.Models.Category>)ViewData["categoryList"];
                foreach (var category in categoryList)
                {
                    if (category.id == Model.categoryId)
                    {
                        <p>@category.name</p>
                    }
                }
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.picture)
        </dt>

        <dd>
            <img src="@Url.Content(Model.picture)" width="250" height="250" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Wallnut-SuperMarket/Views/Items/Details.cshtml
@model Wallnut_SuperMarket.Models.Item

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.counterId)
        </dt>

        <dd>
            @{
                var counterList = (List<Wallnut_SuperMarket.Models.Counter>)ViewData["counterList"];
                foreach (var counter in counterList)
                {
                    if (counter.id == Model.counterId)
                    {
                        <p>@counter.counter1</p>
                    }
                }
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoryId)
        </dt>

        <dd>
            @{
                var categoryList = (List<Wallnut_SuperMarket.Models.Category>)ViewData["categoryList"];
                foreach (var category in categoryList)
                {
                    if (category.id == Model.categoryId)
                    {
                        <p>@category.name</p>
                    }
                }
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.picture)
        </dt>

        <dd>
            <img src="@Url.Content(Model.picture)" width="250" height="250" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Wallnut-SuperMarket/Views/Items/Edit.cshtml
@model Wallnut_SuperMarket.Models.Item

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.counterId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control" id="counterId" name="counterId">
                    <option value="0">Select a counter</option>
                    @{
                        var counterList = (List<Wallnut_SuperMarket.Models.Counter>)ViewData["counterList"];
                        foreach (var counter in counterList)
                        {
                            if (counter.id == Model.counterId)
                            {
                                <option value="@counter.id" selected>@counter.counter1</option>
                            }
                            else
                            {
                                <option value="@counter.id">@counter.counter1</option>
                            }
                        }
                    }
                </select>
                @Html.ValidationMessageFor(model => model.counterId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control" id="categoryId" name="categoryId">
                    <option value="0">Select a category</option>
                    @{
                        var categoryList = (List<Wallnut_SuperMarket.Models.Category>)ViewData["categoryList"];
                        foreach (var category in categoryList)
                        {
                            if (category.id == Model.categoryId)
                            {
                                <option value="@category.id" selected>@category.name</option>
                            }
                            else
                            {
                                <option value="@category.id">@category.name</option>
                            }
                        }
                    }
                </select>
                @Html.ValidationMessageFor(model => model.categoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                @Html.HiddenFor(model => model.picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Wallnut-SuperMarket/Views/Items/Index.cshtml
@model IEnumerable<Wallnut_SuperMarket.Models.Item>

@{
    ViewBag.Title = "Index";
}

<h2>All Items</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.counterId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.categoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.picture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.stock)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @{
                var counterList = (List<Wallnut_SuperMarket.Models.Counter>)ViewData["counterList"];
                foreach (var counter in counterList)
                {
                    if (counter.id == item.counterId)
                    {
                        <p>@counter.counter1</p>
                    }
                }
            }
        </td>
        <td>
            @{
                var categoryList = (List<Wallnut_SuperMarket.Models.Category>)ViewData["categoryList"];
                foreach (var category in categoryList)
                {
                    if (category.id == item.categoryId)
                    {
                        <p>@category.name</p>
                    }
                }
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.rating)
        </td>
        <td>
            <img src="@Url.Content(item.picture)" width="150" height="150" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.stock)
        </td>
        <td>
            @Html.ActionLink("Add Stock", "AddStock", new { id = item.id }) |
            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
            @Html.ActionLink("Details", "Details", new { id = item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.id })
        </td>
    </tr>
}

</table>